services:
  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    ports: -80:80

  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    ports: -3000:3000
