version: "3"
services:
  server:
    build:

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports :
      - 3000:3000
    container_name: client

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 3001:3001
    container_name: server
