version: "3.8"
services:
  server:
    build:
      context: "./server"

      dockerfile: Dockerfile
    ports: -80:80

  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    ports: -3000:3000
