blersion: "3.8"
services:

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    env_file: 
      - ./server/.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 8080:8080
  
  server:
    depends_on:
      - db
    build:
      context: ./server 
      dockerfile: Dockerfile
    env_file: 
      - ./server/.env
    ports:
      - 3001:3001
    environment:
      DB_HOST: db
      DB_USER: $MYSQLDB_USER
      DB_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      DB_NAME: $MYSQLDB_DATABASE
      # - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    stdin_open: true
    container_name: client



