version: "3.8"
services:

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=dockertest
    ports:
      - 8080:8080
  
  server:
    depends_on:
      - db
    build:
      context: ./server 
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - DB_HOST=172.19.0.3
      - DB_USER=chris
      - DB_PASSWORD=pass 
      - DB_NAME=dockertest
      - DB_PORT=3306
    stdin_open: true
    tty: true

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    stdin_open: true
    container_name: client



