version: "3.8"
services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    stdin_open: true
    container_name: client

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 3001:3001
    container_name: server

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example