version: "3.8"
services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    stdin_open: true
    container_name: client

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 3001:3001
    container_name: server

  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # ports: 
    #   - 3306:3306
    expose:
      - 3306

    environment:
      MYSQL_DATABASE: dockertest
      MYSQL_USER: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"