name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-client:
    runs-on: ubuntu latest

    steps:
      - run: echo Hello world!
  build-server:
    runs-on: ubuntu latest

    steps:
      - run: echo Hello world!
